# Generated by ChatGPT.
# Feel free to modify mercilessly for the purpose of the workshop.

def main():
    counter = 0
    print("Simple Counter")
    print("Type 'inc' to increment, 'exit' to quit.\n")

    while True:
        command = input("Command: ").strip().lower()
        if command == "inc":
            counter += 1
            print(f"Counter is now: {counter}")
        elif command == "exit":
            print("Goodbye!")
            break
        else:
            print("Unknown command.")

if __name__ == "__main__":
    main()